spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project2  # change this to your own jdbc url
    username: postgres  # change this to your own username (avoid using a superuser)
    password: huarui66  # change this to your own password
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 180000
      leak-detection-threshold: 120000

logging:
  level:
    root: info
    io.sustc: debug

---

benchmark:
  data-path: data
  student-mode: true
